### ISSUE TITLE
Playing Spotify on cast device

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#11]
Try to play Spotify on cast device (Google home mini) but music does not start. It was already working but not anymore...

In the log I got a timeout:

2021-01-02 11:19:25,664 - ERROR - Google_Home_Mini_Julia: Failed to play spotify track Traceback (most recent call last): File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/googlecast/googlecast.py", line 302, in playSpotify await utils.run_blocking(functools.partial(sp.launch_app)) File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/utils.py", line 29, in run_blocking return await asyncio.get_event_loop().run_in_executor(pool, function) File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/opt/fhem/.local/lib/python3.7/site-packages/pychromecast/controllers/spotify.py", line 89, in launch_app "Timeout when waiting for status response from Spotify app"

**Comment by dominikkarall** [comment]
Hi,
does it work on other googlecast devices? Do you have the same sp_dc and sp_key values for all your googlecast devices?

**Comment by jfmennedy** [comment]
I´ve got the same values for all devices. Its not working on Google Home Google Home Mini and Chromecast Devices.

Readings are changing but does not start to play, List of a device:

Internals:
   CASTNAME   Bureau
   DEF        googlecast 'Bureau'
   FUUID      5f7ff470-f33f-7f5e-d8fb-4ac803b892f29f91
   IODev      local_pybinding
   NAME       Google_Home_Mini_Bureau
   NR         1137
   PYTHONTYPE googlecast
   STATE      online
   TYPE       PythonModule
   READINGS:
     2021-01-02 14:05:58   app_id          CC32E753
     2020-12-30 11:34:54   cast_type       audio
     2021-01-02 03:52:51   connection      connected
     2021-01-02 14:05:58   display_name    Spotify
     2021-01-02 14:05:58   icon_url        https://lh3.googleusercontent.com/HOX9yqNu6y87Chb1lHYqhKVTQW43oFAFFe2ojx94yCLh0yMzgygTrM0RweAexApRWqq6UahgrWYimVgK
     2020-12-30 11:34:54   ignore_cec      0
     2020-12-30 21:09:31   mediaAlbum      
     2020-12-30 21:09:31   mediaArtist     
     2020-12-30 21:09:31   mediaContentId  
     2020-12-30 21:09:31   mediaContentType 
     2020-12-30 21:09:31   mediaCurrentPosPercent 
     2020-12-30 21:09:31   mediaCurrentPosition 
     2020-12-30 21:09:31   mediaDuration   
     2020-12-30 21:09:31   mediaImageHeight 
     2020-12-30 21:09:31   mediaImageUrl   
     2020-12-30 21:09:31   mediaImageWidth 
     2020-12-30 21:09:31   mediaPlayerState UNKNOWN
     2020-12-30 21:09:31   mediaStreamType UNKNOWN
     2020-12-30 21:09:31   mediaTitle      
     2020-12-30 11:34:54   model_name      Google Home Mini
     2020-12-30 12:31:33   mute            0
     2020-12-30 11:34:54   name            Bureau
     2021-01-02 14:05:58   session_id      astertwer-rterte-41ff-reter-wertwertwer
     2021-01-01 02:04:33   spotify_user    my .username(my@email.com)
     2021-01-02 03:52:51   state           online
     2021-01-02 14:05:58   status_text     Spotify
     2021-01-02 14:05:58   transport_id    adsads-asdda-asdasd-rr-rew
     2020-12-30 11:34:54   uuid            wre-7397-rwe-ea12-rwerwer
     2021-01-01 16:08:27   volume          10
   args:
     Google_Home_Mini_Bureau
     PythonModule
     googlecast
     Bureau
   argsh:
Attributes:
   DbLogExclude .*
   IODev      local_pybinding
   alias      Bureau
   favorite_1 http://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3
   favorite_2 https://radios.rtbf.be/pure-128.mp3
   favorite_3 http://spoonradio.ice.infomaniak.ch/spoonradio-hd.mp3
   favorite_4 http://radios.rtbf.be/classic21-128.mp3
   favorite_5 https://open.spotify.com/playlist/37i9dQZF1DX0zmsulfyDdq
   group      GoogleCast
   icon       gassistant
   room       77_GoogleCast,33_Bureau
   spotify_sp_dc SP_DC_kasöopfgdogsdoiasopd
   spotify_sp_key SP_KEY_skpoerwo-b12a-412e3b444e1e
   userattr   Status Status_map favorite_1 favorite_2 favorite_3 favorite_4 favorite_5 strPythonModuleDevices strPythonModuleDevices_map structexclude
   webCmd     playFavorite:play:pause:stop:volume

**Comment by jfmennedy** [comment]
I just found out that my sp_dc and sp_key changed... I dont know since when, but i started my 3 month trial for premium when i realized thta it works with the binding... perhaps that changed the values?

**Comment by dominikkarall** [comment]
The keys should remain for 1 year active. You just need to take them once and they don't need to be from the machine running FHEM/fhempy.
Have you tried to set the new ones? Does it work with them?

**Comment by jfmennedy** [comment]
Yes for now it works again. No Idea why it didnt work before. I perforemed a restart after renewing the keyfiles... i am asking myself, if i could use on each cast device another key file, if  i create a family account and link the different devices with different accounts, so my two daughters could listen to their own music at the same time...

**Comment by dominikkarall** [comment]
Of course, just log in with the account you want to use and set the proper sp_dc/key attributes.

Somebody on the forum had the same issue, that he had to set the attributes again. Maybe they are invalidated as soon as another login happens via Spotify Web.

**Comment by dominikkarall** [comment]
I'm going to close this one, feel free to reopen if it happens again.

**Comment by jfmennedy** [comment]
Will try the family after my 3 month free and keep you up to date ;-) Thx :-)
