### ISSUE TITLE
OSError: [Errno 98] error while attempting to bind on address: address already in use

### ISSUE THREAD

**Issue by GitHubStephan** [dominikkarall/fhempy#26]
Hello,

after FHEM update and PIP update i got same error every 30 seconds. In fhem-log there are the following lines:
2021.08.28 19:15:28 3: Pythonbinding_15733: starting
2021.08.28 19:15:28 3: Pythonbinding_15733: using logfile: ./log/fhempy-2021-08-28.log
2021.08.28 19:15:29 3: Pythonbinding_15733: read: end of file reached while sysread
2021.08.28 19:15:29 3: Pythonbinding_15733: stopped

in fhempy-log:
Traceback (most recent call last):
  File "FHEM/bindings/python/bin/fhempy", line 113, in <module>
    fpb.run()
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py", line 468, in run
    pybinding, "0.0.0.0", port, ping_timeout=None, ping_interval=None
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/asyncio/tasks.py", line 603, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/fhem/.local/lib/python3.7/site-packages/websockets/legacy/server.py", line 1071, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1378, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 15733): address already in use

**Comment by dominikkarall** [comment]
Hi,
it seems that another fhempy instance is running already.

Please execute
```
sudo -u fhem pip3 install fhempy==0.1.103
```
Restart FHEM afterwards.

**Comment by GitHubStephan** [comment]
Command and restart done but error still occurs

**Comment by GitHubStephan** [comment]
few minutes ago i saw that there was again a new FHEM update for pythonbinding. i did it and after fhem restart it seems that the log-error is gone now.
