### ISSUE TITLE
can not connect to Device

### ISSUE THREAD

**Issue by Heiner1967** [dominikkarall/fhempy#34]
Hi, I have some trouble with Tuya as well as with Tuya Cloud. Likly due to all this ID I strugle to use the right one.

in Tuya IOT Platform I am able to link to my Tuya App, which is afterwards visible from both ends ( IOT Platform as well as inside the App) as a result I can see a UID inside IOT Platform

However I am not able to see the Device which is visible and function with no problem inside Tuya App. I guess here is already the Error.
Inside the Tuya App there is a Virtuell-ID, and IP, a MAC and the TimeZone Europe/Berlin.
Inside IOT Patform the Device Management is on Western Europe ( after adding Central Europe the Device is visible inside IOT Platform)

in fhem tuya_system shows "ready" but no device is found
likly the DeviceID used is wrong, it is neither the  Virtual ID inside the Tuya App, nor the UID of the linked Tuya App.

In the individual Device setup I struggle to identify the Product-ID and I do not get the difference of DEVICE_ID and LOCAL_KEY

Now i struggle to see what to do next.

I hope you have a hint for me. Many Thanks.

**Comment by dominikkarall** [comment]
Hi,
do you see the device you can control with tuya app in the iot platform? If so, please post the define of your tuya_cloud setup device (please remove the password).

**Comment by Heiner1967** [comment]
Yes I see it:

Device Name | Device ID | Product | Association | Online Status | Activation Time | Operation
-- | -- | -- | -- | -- | -- | --
Elitecho-GU10 5.5W RGBCCT W | 150028062cf432edf33a | Elitecho-GU10 5.5W RGBCCT W | x.y@z.com | Online | 2021-09-06 20:10:18 | Debug Device

In fhem I tried to define with this:
tuya 150028062cf432edf33a 150028062cf432edf33a 217.254.242.5 150028062cf432edf33a 3.32 AccessID AccessSecret 

The IP I got from the Tuya App, suprisinlgy different to the rest of my Homenetwork IP

**Comment by dominikkarall** [comment]
Btw, you should use only tuya_cloud. I wouldn't recommend tuya module as it is not event based and therefore doesn't readings aren't updated immediately.

**Comment by dominikkarall** [comment]
Please use tuya_cloud instead of tuya module.

**Comment by Heiner1967** [comment]
May be worth to mention the Tuya 
-system DeviceID is mention as 0 !!!! I used in the definition the UID of the Tuya Appl link, same result I get if I use the Device ID as per last post....

I guess here is something wrong and hence the scan is not working

**Comment by Heiner1967** [comment]
ok, Cloud connector is defined with:
tuya_cloud setup vAccessID AcessSecret Username Passwort tuyaSmart CentralEurope

**Comment by dominikkarall** [comment]
Yes, what's the result?

**Comment by Heiner1967** [comment]
failed to connect

**Comment by dominikkarall** [comment]
Please just do a define of tuya_cloud setup ...

Post the log output and the readings. If you get failed to connect, you need to check the clientid, secret, username and password again.

**Comment by Heiner1967** [comment]
just deleted all tuya Module related.
I go to verbose 5. The Log says:
`2021-09-27 22:34:54,880 - ERROR    - fhempy.lib.fhem_pythonbinding: Failed to handle message: 
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py", line 389, in _onMessage
    await self.sendBackReturn(hash, ret)
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py", line 95, in sendBackReturn
    await self.wsconnection.send(msg.encode("utf-8"))
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 631, in send
    await self.write_frame(True, opcode, data)
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 1188, in write_frame
    await self.drain()
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 1177, in drain
    await self.ensure_open()
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2021-09-27 22:34:54,930 - ERROR    - fhempy.lib.fhem_pythonbinding: Connection closed error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 1148, in read_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py", line 67, in pybinding
    async for message in websocket:
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 481, in __aiter__
    yield await self.recv()
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2021-09-27 22:34:54,935 - INFO     - fhempy.lib.fhem_pythonbinding: Restart binding
2021-09-27 22:34:54,937 - INFO     - websockets.server: connection closed
2021-09-27 22:35:00,059 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2021-09-27 22:35:00,129 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2021-09-27 22:35:00,419 - WARNING  - asyncio: Executing <Task pending coro=<async_main() running at /opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py:462> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0xb5b2b210>()] created at /usr/lib/python3.7/asyncio/tasks.py:615> cb=[_run_until_complete_cb() at /usr/lib/python3.7/asyncio/base_events.py:158] created at /usr/lib/python3.7/asyncio/base_events.py:563> took 0.360 seconds
2021-09-27 22:35:00,429 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2021-09-27 22:35:06,337 - INFO     - websockets.server: connection open
2021-09-27 22:35:06,347 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
2021-09-27 22:35:06,429 - WARNING  - asyncio: Executing <Handle <TaskWakeupMethWrapper object at 0xb5b2b3b0>(<Future finis...events.py:396>) created at /usr/lib/python3.7/asyncio/streams.py:408> took 0.100 seconds
2021-09-27 22:35:15,457 - ERROR    - tuya_cloud_connector: Tuya login error response: {'code': 1106, 'msg': 'permission deny', 'success': False, 't': 1632774915427}`

**Comment by dominikkarall** [comment]
2021-09-27 22:35:15,457 - ERROR - tuya_cloud_connector: Tuya login error response: {'code': 1106, 'msg': 'permission deny', 'success': False, 't': 1632774915427}`

When did you create the tuya iot platform project? It needs to be created later than May 2021. If you just created it a few days ago you need to check clientid/secret, username/password again.

**Comment by Heiner1967** [comment]
As username I take "Spitzname" from the Tuya App, thats the only name I have, if i take my Email, it's colored inside definition editor and does not work either

**Comment by dominikkarall** [comment]
Could it be that you registered with Google instead of registering an account?

**Comment by Heiner1967** [comment]
IOT platform project is now about 1 week old
I registered based on a gmail Mailadress in IOT Platform as well as in the Tuya App

**Comment by dominikkarall** [comment]
You need to register an account and use the email address. You can find the username here (in my case the email address domi****.com - of course you need to use the full one)

![image](https://user-images.githubusercontent.com/16180589/134982505-36ab720d-8b6b-4a50-aeb9-20543fcb451c.png)

**Comment by Heiner1967** [comment]
clientID/secret is thhis in the overview, correct?

Access ID/Client ID: 
Access Secret/Client Secret

checked

**Comment by dominikkarall** [comment]
> clientID/secret is thhis in the overview, correct?
> 
> Access ID/Client ID:
> Access Secret/Client Secret
> 
> checked

yes

**Comment by Heiner1967** [comment]
if I use this Mail, in fhem definition the portion @gmail is marked in red, as well the last character of my Password which is this:& is marked in orange.

Do I need to do the registration with another Mailprovider?

**Comment by dominikkarall** [comment]
no, it's actually not fhem which is marking it red, it might be just your browser which is doing a spellcheck.

**Comment by dominikkarall** [comment]
is the status "ready" now?

**Comment by Heiner1967** [comment]
Hi,

sorry neede to leave yesterdy night. No it is not.
Still failed to connect. With verbose 5 the fhem log says
`2021.09.28 20:07:51 3: PythonModule v1.0.0 (tuya_cloud)
2021.09.28 20:07:51 4: PythonModule: fhempy not yet connected! Define will continue after connect...`

Access ID and AccessSecret per copy paste added in.
neither Email as per TuyaApp nor "Spitzname" as per Tuya app does work , password (of Tuya App) checked once more
rest of the define is "tuyaSmart Europe" - should be correct as well, the Device is visible in IOT Platform as Central Europe, not Western Europe.

**Comment by Heiner1967** [comment]
I get crazy, I defined a second connector, same parameter all put in by copy paste and it works.
I thought i am stupid and copied paste both definitions below each other and all characters match. MEans a updated definition is not resulting in the same as a new definition !!!!

**Comment by dominikkarall** [comment]
it is defined automatically. Try to restart fhempy (Pythonbinding_15733) as it will load all devices from the cloud again.

**Comment by Heiner1967** [comment]
ok, i restarted, the connector goes into Connecting and after a while to PytonBinding timeout.
no device created.

fhempylog says
2021-09-28 20:44:48,430 - ERROR    - tuya iot: Unexpected disconnection.1
[2021-09-28 20:44:49,572] [tuya-openmq] Unexpected disconnection.1
2021-09-28 20:44:49,572 - ERROR    - tuya iot: Unexpected disconnection.1
2021-09-28 20:44:53,812 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2021-09-28 20:44:53,978 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2021-09-28 20:44:54,344 - WARNING  - asyncio: Executing <Task pending coro=<async_main() running at /opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py:462> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0xb5b4c1b0>()] created at /usr/lib/python3.7/asyncio/tasks.py:615> cb=[_run_until_complete_cb() at /usr/lib/python3.7/asyncio/base_events.py:158] created at /usr/lib/python3.7/asyncio/base_events.py:563> took 0.531 seconds
2021-09-28 20:44:54,360 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2021-09-28 20:45:00,620 - INFO     - websockets.server: connection open
2021-09-28 20:45:00,631 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1

**Comment by dominikkarall** [comment]
Have you updated to the latest version? Timeout should have been fixed since about 1 or 2 weeks. Please do an update command in FHEM and restart FHEM afterwards.

**Comment by Heiner1967** [comment]
ok updated and restarted, no new device, restart pybinding again, no new device
fhempylog says
2021-09-28 21:23:32,099 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2021-09-28 21:23:32,143 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2021-09-28 21:23:32,298 - WARNING  - asyncio: Executing <Task pending coro=<async_main() running at /opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py:462> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0xb5bba0d0>()] created at /usr/lib/python3.7/asyncio/tasks.py:615> cb=[_run_until_complete_cb() at /usr/lib/python3.7/asyncio/base_events.py:158] created at /usr/lib/python3.7/asyncio/base_events.py:563> took 0.199 seconds
2021-09-28 21:23:32,305 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2021-09-28 21:23:40,639 - INFO     - websockets.server: connection open
2021-09-28 21:23:40,656 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
fhemlog
2021.09.28 21:23:29 3: Pythonbinding_15733: read: end of file reached while sysread
2021.09.28 21:23:29 3: Pythonbinding_15733: stopped
2021.09.28 21:23:29 3: Pythonbinding_15733: starting
2021.09.28 21:23:29 3: Pythonbinding_15733: using logfile: ./log/fhempy-2021-09-28.log
2021.09.28 21:23:29 1: ws:127.0.0.1:15733 disconnected, waiting to reappear (local_pybinding)
2021.09.28 21:23:30 1: BindingsIo: ERROR local_pybinding - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2021.09.28 21:23:40 1: ws:127.0.0.1:15733 reappeared (local_pybinding)
2021.09.28 21:23:46 1: PERL WARNING: Use of uninitialized value in string eq at (eval 6526) line 1.
2021.09.28 21:23:46 3: Please define Elitecho-GU10_5.5W_RGBCCT_W_150028062cf432edf33a first

**Comment by dominikkarall** [comment]
Please post the fhempy log with tuya_cloud setup device verbose=5. Do a restart after that to have a clean log.

**Comment by dominikkarall** [comment]
Can you please try
define Elitecho-GU10_5.5W_RGBCCT_W_150028062cf43xxxxxan dummy

I think the bug might be the length of the name.

**Comment by dominikkarall** [comment]
Ok "-" is the character which isn't supported in FHEM. I'll update fhempy to replace that one.

**Comment by dominikkarall** [comment]
Please do
```
set local_pybinding update
```
and wait till update is finished. It's finished when local_pybinding is opened again. This might take up to some minutes.

After that your device should be available.

**Comment by Heiner1967** [comment]
Hurra, it works 🥇 
Many Thanks for creating fhempy and many more thanks for getting this thing for me to work.

Thats super cool now

**Comment by dominikkarall** [comment]
Perfect 👍
