### ISSUE TITLE
Logfile error

### ISSUE THREAD

**Issue by Heiner1967** [dominikkarall/fhempy#36]
Hi,
I still do recieve a LogEntry on this Tuya Device where you helped me with to get it to work.

Every 5 min this comes:
2021-09-30 06:24:14,453 - ERROR    - Elitecho_GU10_5.5W_RGBCCT_W_150028062cf432edf33a: string indices must be integers
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/tuya_cloud/tuya_cloud_device.py", line 291, in update_readings_dict
    await self.update_readings_hsv(st_name, status_dic[st_name])
  File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/tuya_cloud/tuya_cloud_device.py", line 312, in update_readings_hsv
    int(hsv_json["h"]) / 360,
TypeError: string indices must be integers

In principle anything seems to work however but I wonder if I could do something about this?

**Comment by dominikkarall** [comment]
Thanks for reporting!

Please try with 0.1.125, it should be fixed there.

**Comment by Heiner1967** [comment]
I did a update all yesterday night but I am still on V 0.1.123

**Comment by dominikkarall** [comment]
set local_pybinding update

**Comment by Heiner1967** [comment]
Hi, sorry but it did not work.

initialy the state shows updating but finaly it is back on 0.1.123.

fhem lof says:
2021.10.06 10:03:50 1: ws:127.0.0.1:15733 disconnected, waiting to reappear (local_pybinding)
2021.10.06 10:03:50 3: Pythonbinding_15733: read: end of file reached while sysread
2021.10.06 10:03:50 3: Pythonbinding_15733: stopped
2021.10.06 10:03:50 3: Pythonbinding_15733: starting
2021.10.06 10:03:50 3: Pythonbinding_15733: using logfile: ./log/fhempy-2021-10-06.log
2021.10.06 10:03:50 1: BindingsIo: ERROR local_pybinding - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2021.10.06 10:04:02 1: ws:127.0.0.1:15733 reappeared (local_pybinding)

fhempylog says:
2021-10-06 10:01:28,137 - WARNING  - asyncio: Executing <Handle _SelectorDatagramTransport._read_ready() created at /usr/lib/python3.7/asyncio/selector_events.py:249> took 0.180 seconds
2021-10-06 10:01:29,915 - WARNING  - asyncio: Executing <Handle _SelectorDatagramTransport._read_ready() created at /usr/lib/python3.7/asyncio/selector_events.py:249> took 0.120 seconds
2021-10-06 10:01:36,315 - WARNING  - asyncio: Executing <TimerHandle when=54966.530794746 AsyncEngine._async_cache_cleanup() created at /usr/local/lib/python3.7/dist-packages/zeroconf/_core.py:177> took 0.105 seconds
2021-10-06 10:01:44,106 - WARNING  - asyncio: Executing <Handle _SelectorDatagramTransport._read_ready() created at /usr/lib/python3.7/asyncio/selector_events.py:249> took 0.194 seconds
2021-10-06 10:02:55,888 - INFO     - fhempy.lib.pkg_installer: Attempting install of fhempy
2021-10-06 10:03:50,753 - ERROR    - fhempy.lib.pkg_installer: Unable to install package fhempy: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 572, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 530, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 675, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 793, in _get_page
    return _get_html_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 144, in _get_html_page
    "Cache-Control": "max-age=0",
  File "/usr/share/python-wheels/requests-2.21.0-py2.py3-none-any.whl/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/_internal/download.py", line 396, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.21.0-py2.py3-none-any.whl/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.21.0-py2.py3-none-any.whl/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 37, in send
    cached_response = self.controller.cached_request(request)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/controller.py", line 111, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 114, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/serialize.py", line 176, in _loads_v2
    cached = json.loads(zlib.decompress(data).decode("utf8"))
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
2021-10-06 10:03:53,530 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2021-10-06 10:03:53,577 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2021-10-06 10:03:53,787 - WARNING  - asyncio: Executing <Task pending coro=<async_main() running at /opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py:462> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0xb5ba6290>()] created at /usr/lib/python3.7/asyncio/tasks.py:615> cb=[_run_until_complete_cb() at /usr/lib/python3.7/asyncio/base_events.py:158] created at /usr/lib/python3.7/asyncio/base_events.py:563> took 0.257 seconds
2021-10-06 10:03:53,795 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2021-10-06 10:04:01,977 - INFO     - websockets.server: connection open
2021-10-06 10:04:01,985 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1

**Comment by dominikkarall** [comment]
Please try
```
sudo -u fhem bash
pip3 install --upgrade fhempy
```
Post the output afterwards.
