### ISSUE TITLE
Miio Vacuum

### ISSUE THREAD

**Issue by xerion3800** [dominikkarall/fhempy#68]
Hallo beim erstellen des Device miio_vacuum bekomme ich immer folgenden Fehler:

```
Failed to execute function Define: Traceback (most recent call last): File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py", line 381, in _onMessage fct_timeout, File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for return fut.result() File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/miio/miio.py", line 82, in Define helptext + "
Arguments: " + " ".join(self._set_list[dev_cmd]["help"]) TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by dominikkarall** [comment]
Sollte hiermit gefixt sein:
https://github.com/dominikkarall/fhempy/commit/e22c55cf8654791895f6b220b349f1044a9c008b

Bitte um Update und Check.

**Comment by xerion3800** [comment]
Funktioniert. Danke.
