### ISSUE TITLE
Tuya not working anymore

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#77]
HI Dominik, I made the update from 0.1.293 to recent 0.1.329 and my tuya devices won't work anymore..

The state is following error:

Failed to load module tuya: Traceback (most recent call last): File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 214, in handle_function module_object = await self.import_module(hash) File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 393, in import_module module_object = await utils.run_blocking( File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 34, in run_blocking return await asyncio.get_event_loop().run_in_executor(pool, function) File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1030, in _gcd_import File "<frozen importlib._bootstrap>", line 1007, in _find_and_load File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 680, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 790, in exec_module File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 7, in <module> import tinytuya File "/home/pi/.local/lib/python3.9/site-packages/tinytuya/__init__.py", line 99, in <module> import requests File "/home/pi/.local/lib/python3.9/site-packages/requests/__init__.py", line 133, in <module> from . import utils File "/home/pi/.local/lib/python3.9/site-packages/requests/utils.py", line 28, in <module> from ._internal_utils import to_native_string File "/home/pi/.local/lib/python3.9/site-packages/requests/_internal_utils.py", line 11, in <module> from .compat import is_py2, builtin_str, str ImportError: cannot import name 'builtin_str' from partially initialized module 'requests.compat' (most likely due to a circular import) (/home/pi/.local/lib/python3.9/site-packages/requests/compat.py)

**Comment by dominikkarall** [comment]
Hi,
please try to restart fhempy. It looks like a circular import, as it depends on timings it sometimes works on the second restart.
I'll check it later.

Do you use API key/secret as well in the define?

**Comment by jfmennedy** [comment]
I already tried to restart several times.. I use the definition like this:

define wifi_plug fhempy tuya PRODUCT_ID DEVICE_ID IP LOCAL_KEY [VERSION]

**Comment by dominikkarall** [comment]
Can you please check with 0.1.330. I adapted the tinytuya import.

**Comment by jfmennedy** [comment]
Still not working in latest version..

This is the log: 

Mai 10 07:16:39 pi fhempy[464]: Traceback (most recent call last):
Mai 10 07:16:39 pi fhempy[464]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 403, in create_device
Mai 10 07:16:39 pi fhempy[464]:     await self._create_cloudmapping_dev()
Mai 10 07:16:39 pi fhempy[464]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 320, in _create_cloudmapping_dev
Mai 10 07:16:39 pi fhempy[464]:     await self.retrieve_tuya_specs()
Mai 10 07:16:39 pi fhempy[464]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 296, in retrieve_tuya_specs
Mai 10 07:16:39 pi fhempy[464]:     spec = await self.get_tuya_dev_specification()
Mai 10 07:16:39 pi fhempy[464]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 255, in get_tuya_dev_specification
Mai 10 07:16:39 pi fhempy[464]:     functools.partial(self.tuya_cloud.getdps, self.tt_did)
Mai 10 07:16:39 pi fhempy[464]: AttributeError: 'NoneType' object has no attribute 'getdps'
Mai 10 07:16:39 pi fhempy[464]: 2022-05-10 07:16:39,837 - ERROR    - wzKonvektor: Failed create_device

**Comment by dominikkarall** [comment]
Please test 0.1.332, should be fixed.

**Comment by jfmennedy** [comment]
Thank you, it is fixed 👍
